# Generated by Django 3.1.3 on 2021-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20210515_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.CharField(max_length=3),
        ),
    ]
