# Generated by Django 3.1.3 on 2021-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20210612_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
