# Generated by Django 3.1.3 on 2021-06-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20210419_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
